# Even Fibonacci numbers Problem 2

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

def fibonacci(a, b):
    while True:
        yield a
        a, b = b, a+b

def is_even(n):
    return n % 2 == 0

def main(max_num):
    fib_sum = 0
    for f in fibonacci(1, 2):
        if f >= max_num:
            break
        elif is_even(f):
            fib_sum += f
    return fib_sum

if __name__ == '__main__':
    print(main(4000000))
